#!/usr/bin/env node
// Reads src/web/public/{index.html,style.css,app.js} and writes
// src/web/assets.generated.ts with a single INLINE_HTML export.
// Must run before tsup so the pkg binary has the UI baked in.

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root   = join(dirname(fileURLToPath(import.meta.url)), '..');
const pubDir = join(root, 'src/web/public');

const html = readFileSync(join(pubDir, 'index.html'), 'utf-8');
const css  = readFileSync(join(pubDir, 'style.css'),  'utf-8');
const js   = readFileSync(join(pubDir, 'app.js'),     'utf-8');

// Inline CSS and JS into the HTML so it's fully self-contained
const inlined = html
  .replace('<link rel="stylesheet" href="style.css">', `<style>\n${css}\n</style>`)
  .replace('<script src="app.js"></script>', `<script>\n${js}\n</script>`);

// Escape backticks and ${} so it's safe inside a template literal
const escaped = inlined.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const out = `// AUTO-GENERATED by scripts/inline-assets.mjs — do not edit manually
export const INLINE_HTML = \`${escaped}\`;
`;

const outPath = join(root, 'src/web/assets.generated.ts');
writeFileSync(outPath, out, 'utf-8');
console.log('  → inlined web assets into src/web/assets.generated.ts');
